[build]
  functions = "functions"
  command = "netlify-lambda install && mkdir ./public"
[template.environment]
  FAUNA_SECRET_KEY = "fnAD1oqhHJACAZW75LILehH5FT7wOf9wuwC8C8xP"
  TELEGRAM_BOT_TOKEN = "Telegram bot token here"
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
